

class LocatorsPage():
    def __init__(self, page):
        self.page = page

    SIGN_IN = ".navbar__item_signIn"
    LOGIN_OR_EMAIL = "#login"
    PASSWORD = "#password"
    SIGN_IN_BUTTON = ".L6xZMB.yo9FdR"
    MENU_TOOLS = "//a[@data-dropdown='tools' and normalize-space(text())='Tools']"
    MENU_SERVICES = "//a[@data-dropdown='services' and normalize-space(text())='Services']"
    CONTAINER_TRACKING_MENU = "xpath=//p[@class='dropMenu__title' and normalize-space()='Container Tracking']""/ancestor::a[1]"
    REQUEST_A_QUOTE_MENU = "//div[@class='dropMenu__content drop-services__content js-drop-content']//span[@class='dropMenu__item__request__title'][normalize-space()='Request a quote']"
    CONTAINER_TRACKING_APP = ".app-root-unified_tracking"
    REQUEST_APP = ".F2Sj4"
    UPDATE_BUTTON_CT = ".ZsFQOW"
    INPUT_CT_APP = "[data-test-id='search-input']"
    SEARCH_BUTTON_CT = "[data-test-id='search-button']"
    FOLLOW_BUTTON = "[data-test-id^='card-action-follow']"
    ROUTE_BUTTON = "button:has-text('Route')"
    OPEN_CARD = "[data-test-id^='card-action-open']"
    DELETE_CARD_BUTTON = "[data-test-id^='card-action-delete']"
    CONFIRM_DELETE_CARD_BUTTON = "button:text-is('Delete')"
    CT_LIST_CARD = "#mainView"
    FIRST_CARD = "[data-test-id^='card-action-open']"
    RATE_SWIPER = ".swiper-wrapper"
    BOOK_NOW_IN_SWIPER = "a:text-is('Book now')"
    REQUEST_QUOTA_IN_SWIPER = "a:text-is('Request a quote')"
    MAP_PREBOOK_PAGE = ".maplibregl-canvas"
    RQ_CARGO_DETAILS_LOCATOR = "h1:text-is('Cargo details')"
    UPLOAD_FILE_MENU_CT = "[data-test-id='upload-file-button']"
    UPLOAD_FILE_INPUT = "input[type='file'][accept*='spreadsheetml.sheet']"
    EMPTY_TEMPLATE = "[data-test-id='upload-file-empty-template-link']"
    UPLOAD_FILE_CT = "[data-test-id='upload-file-button']"
    NEXT_BUTTON_UPLOAD_FILE = "button:text-is('Next')"
    SUCCESFULLY_UPLOAD_FILE = "div:text-is('We uploaded all the containers!')"
    ADD_FIRST_TAG_BUTTON = "[data-test-id^='openedCard-action-tags']"
    TAG_INPUT = ".unified-tracking-quTQrO"
    SAVE_BUTTON_TAG = "button[type='button']:has-text('Save')"
    EDIT_TAG_BUTTON = "role=button[name=/^Edit tag(?:\s*\d+)?$/i]"
    BACK_BUTTON = "button[type='button']:has-text('Back')"
    DELETE_TAG_CROSS = ".unified-tracking-_N8c07"
    MODAL_DIALOG = ".unified-tracking-kukEc6"
    COPY_BUTTON = "[data-test-id^='openedCard-action-copy']"
    SETTING_RADIO_BUTTON = ".leaflet-control-layers-toggle"
    STREETS_MAP = "//span[normalize-space(.)='Streets']/preceding-sibling::input[@type='radio']"
    VESSEL_TAB = "[data-test-id^='openedCard-vessels-tab']"
    VOYAGE_IN_VESSEL_TAB = "div:has-text('Voyage')"
    POINT_ON_MAP = ".leaflet-marker-icon:not(:has(.markerClusterLabel))"
    CONTAINER_NUMBER_POINT = ".unified-tracking-NCXSJ2"
    DAILY_LIMIT_MESSAGE = "p[class*='unified-tracking-Zb8z5j']:has-text('Daily request limit reached')"
    PAID_BUTTON_SUBSCRIPTION = "[data-test-id='payments-subscription-button']"
    CREDITS_USED = ".unified-tracking-j4IQ8u"
    PAID_PLAN = "span:text-is('Paid')"
    PURCHASE_CREDITS = "[data-test-id='payments-extend-plan-button']"
    PRO_PLAN = "div:text-is('Pro')"
    ANALYTICS_TAB_BOTTON = "span:text-is('Analytics')"
    CONTENT_ANALYTICS_TAB = ".pieCard__content"
    NOTIFICATION_TAB_BOTTON = "span:text-is('Notifications')"
    CONTENT_NOTIFICATION_TAB = "div:has-text('Latest update')"
    CALENDAR_TAB_BOTTON = "span:text-is('Calendar')"
    CONTENT_CALENDAR_TAB = "[class^='fc-daygrid-day-frame']"
    MAP_TAB_BOTTON = "span:text-is('Map')"
    DAILY_LIMIT_MODAL_TS = '.unified-tracking-xrU1A1'
    REQUEST_IT_QUOTE = "//div[@class='dropMenu__content js-drop-content']//span[@class='dropMenu__text_tools'][normalize-space()='Request an IT quote']"


    HS_CODE_REQUEST = ".a3RkC"


    SERVICES_DROPDOWN = "css=div.drop-services__content"   # контейнер services-меню
    REFERENCES_ACTIVE_SECTION = "css=div[data-dropdown='references'].dropMenu__section_active"
    SERVICES_ACTIVE_SECTION = "css=div[data-dropdown='services'].dropMenu__section_active"  # если есть
    TOOLS_SECTION_ACTIVE = "css=div[data-dropdown='tools'].dropMenu__section_active"